const paragraphs = [
    "TANGINA MO, JHEPOY DIZON! ANG PANGIT NG PAGMUMUKHA MO, KITA MO NA BANG MUKHA MO SA SALAMIN? TANGINA MO! ANG PANGIT MO, HA? Tangina mo! At anong ang sinasabi mong pulubi at taga-hugas ako ng pinggan ha? TANGINA MO! Tignan mo nga bahay ko, BILLAGE YAN, eh-a-at ikaw naman, ano ha? Tangina mo skwater? HA? Nagyayabang ka pang may laptop at kita mo to hampas ko to sa pagmumukha mo eh no? Tangina mo, ha, ha?",
    "Pano ko ba to sisimulan at sasabihin sayo? Hmmff... Pero eto na yung mala KDRAMA kung pabati Sayo ng LONG SWEET MESSAGE for you Babeko. Good Morning Babeko. Pag gising mo Babe, wag mo kakalimutan breakfast mo aa. Ingatz ka kung saan ka man pumunta at sa pagpasok mo aa Babeko. Mag-aral ng mabuti Babeko.To the girlfriend I love the most, I love you Babeko. My future wife ko. Oppss! Wag magalit future wife ko aa. Love you Babeko. Magiging totoo naman yan. Promise, not now but soon. Ito na, di ko na papatagalin pa Babeko, LSM para sayo. Sana Babeko basahin mong mabuti to Babe aa. Medyo may pagka-corny. Wag kang luluha hahaha. Dahil maaabutan tayo ng mga fans natin ayieeehh. Pag tumulo luha mo Babeko, joke lang Babeko. Pinapasaya lang kita.Una sa lahat at hindi sa huli, jk lang. Seryoso na nga Babeko. Ito na talaga. I really do love you.",
    "beh, cr lang ako. no be. don't say that. youre more than just a cr. everytime na maiisip mo na cr lang ako no. youre a wonderful person and we appreciate you so much. hindi biro maging cr. it must've been tough pero you did it. yuore so strong kaya sobrang proud kami sayo.",
    "di ko napansin, Haha sorry sabi ko na nga ba e. Sorry sa istorbo haha. ayaw talaga sakin ng mundo, life is so unfair. Sana hindi nalang ako nag tanong haha. Sensya na ah, eto lang kasi ako. Walang kwenta. Sana di nalang ako pinanganak haha,I'm just a simple person kasi, lowkey. I am just nobody. Walang magkakagusto sa walang kwentang tao katulad ko haha, sana di nalang ako nabuhay.",
    "Pwede pakopya? Ayaw mo? Sige okay lang hindi na lang kita kukulitin sanay naman akong walang tumutulong sakin eh tsaka baka busy ka. Pasensya ka na ha eto lang kasi ako eh, bob0. Sana hindi mo na lang ako naging kaklase no? Hindi kasi ako kasing talino mo. Sana talaga hindi na lang ako pin4nganak.",
    "yeoboseyo ?? I mean hello >.< *chuckles lightly* oh arasso, i mean okay ah .... ne, i mean yes. jinjjayo i mean really ... eheh ..mianhaeyo !!! I'M SORRY *frustated sigh* aish...ottoke i mean what do we do ?? arasso, i mean okay :3 see you annyeong, i mean bye",
    "Allen kalbo, Allen kalbo. Okay sino yung nag-Aallen kalbo? Gusto mong tanggalin kita sa section na to? Di pa tayo nagsisimula kung ano-ano nang ginagawa mo ha, sinabi ko na dati pa respeto. Sino yon? Si ano po yun si Justine Carl Argana nakita ko po siya. Ako?Justine Carl Argana? Opo. Hindi ako yun tang in- o sige mura pa. Yong mga kabastusan niyo itago niyo muna ha, 'di ko pinapalampas yung mga ganyan. 'Di pa tayo nagsisimula e nagagalit na naman ako. Respeto okay",
    "Mga rules ni GBF :1. Kapag sinaktan ka ng girlfriend mo sa'kin ka na lang 2. Dapat pumapayag ka sa mga couple icon 3. Dapat updated ako sa lahat ng mga ginagawa mo 4. Dapat nagsasayaw din tayo ng Heartbreak Anniversary with titig 5. Dapat ako lang GBF mo",
    "mag iingat po tayo sa pagbili ng mga low quality na christmas light this year, may mga tao po ksi na bigla nalang magbibigay ng liwanag sa buhay natin tapos bigla rin mawawala.",
    "f-fuck shit!? shit?!? *kinuha yung sabon* i-ito yung nanakit sayo? *hinampas sa pader yung sabon* d-don't h-hurt m-my p-princess! h-hindi niya k-kailangan m-maligo k-kung ayaw n-niya!! *sinuntok yung pader* I- I k-know t-this is m-my f-fault. don't l- leave m-me *cry silently*",
];